using System.Collections.Generic;
using Kore.Localization;

namespace Kore.Plugins.Messaging.Forums.Infrastructure
{
    public class LanguagePackInvariant : ILanguagePack
    {
        #region ILanguagePack Members

        public string CultureCode
        {
            get { return null; }
        }

        public IDictionary<string, string> LocalizedStrings
        {
            get
            {
                return new Dictionary<string, string>
                {
                    { LocalizableStrings.Account.ForumSubscriptions, "Forum Subscriptions" },
                    { LocalizableStrings.Account.ForumSubscriptions_DeleteSelected, "Delete Selected" },
                    { LocalizableStrings.Account.ForumSubscriptions_Description, "You will receive an e-mail when a new forum topic/post is created." },
                    { LocalizableStrings.Account.ForumSubscriptions_InfoColumn, "Forum/Topic" },
                    { LocalizableStrings.Account.ForumSubscriptions_NoSubscriptions, "You are not currently subscribed to any forums" },
                    { LocalizableStrings.Account.MyAccount, "My Account" },
                    { LocalizableStrings.ActiveDiscussions, "Active Discussions" },
                    { LocalizableStrings.ActiveDiscussions_ViewAll, "View All" },
                    { LocalizableStrings.ActiveDiscussionsFeedDescription, "Topics with active discussions." },
                    { LocalizableStrings.ActiveDiscussionsFeedTitle, "{0} - Active Discussions" },
                    { LocalizableStrings.ActiveDiscussionsRSSLinkTitle, "Click here to be automatically informed of active discussion topics." },
                    { LocalizableStrings.AdvancedSearch, "Advanced Search" },
                    { LocalizableStrings.Author, "Author" },
                    { LocalizableStrings.Breadcrumb.ForumGroupTitle, "Forum Group" },
                    { LocalizableStrings.Breadcrumb.ForumHomeTitle, "Forum Home Page" },
                    { LocalizableStrings.Breadcrumb.ForumTitle, "Forum" },
                    { LocalizableStrings.Breadcrumb.TopicTitle, "Topic" },
                    { LocalizableStrings.By, "By" },
                    { LocalizableStrings.DeletePost, "Delete Post" },
                    { LocalizableStrings.DeleteTopic, "Delete Topic" },
                    { LocalizableStrings.EditPost, "Edit Post" },
                    { LocalizableStrings.EditTopic, "Edit Topic" },
                    { LocalizableStrings.Forum, "Forum" },
                    { LocalizableStrings.ForumFeedDescription, "Forum's topics with newest posts." },
                    { LocalizableStrings.ForumFeedTitle, "{0} - Forum: {1}" },
                    { LocalizableStrings.ForumName, "Forum Name" },
                    { LocalizableStrings.ForumRSSLinkTitle, "Click here to be automatically informed of new posts and topics in the forum." },
                    { LocalizableStrings.Forums, "Forums" },
                    { LocalizableStrings.In, "In" },
                    { LocalizableStrings.Joined, "Joined" },
                    { LocalizableStrings.LatestPost, "Latest Post" },
                    { LocalizableStrings.Location, "Location" },
                    { LocalizableStrings.Models.Pager.CurrentPage, "Current Page" },
                    { LocalizableStrings.Models.Pager.First, "First" },
                    { LocalizableStrings.Models.Pager.Last, "Last" },
                    { LocalizableStrings.Models.Pager.Next, "Next" },
                    { LocalizableStrings.Models.Pager.Previous, "Previous" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.AllResults, "All Results" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.OneDay, "1 Day" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.OneMonth, "1 Month" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.OneYear, "1 Year" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.SevenDays, "7 Days" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.SixMonths, "6 Months" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.ThreeMonths, "3 Months" },
                    { LocalizableStrings.Models.Search.LimitResultsToPrevious.TwoWeeks, "2 Weeks" },
                    { LocalizableStrings.Models.Search.SearchInForum.All, "All Forums" },
                    { LocalizableStrings.Models.Search.SearchWithin.All, "Topic titles and post text." },
                    { LocalizableStrings.Models.Search.SearchWithin.PostTextOnly, "Post text only" },
                    { LocalizableStrings.Models.Search.SearchWithin.TopicTitlesOnly, "Topic titles only" },
                    { LocalizableStrings.Moderator, "Moderator" },
                    { LocalizableStrings.MoveTopic, "Move Topic" },
                    { LocalizableStrings.NewPost, "New Post" },
                    { LocalizableStrings.NewTopic, "New Topic" },
                    { LocalizableStrings.NoPosts, "No Posts" },
                    { LocalizableStrings.NotifyWhenSomeonePostsInThisTopic, "Notify me via email when someone posts in this topic." },
                    { LocalizableStrings.Pager.FirstPageTitle, "First Page" },
                    { LocalizableStrings.Pager.LastPageTitle, "Last Page" },
                    { LocalizableStrings.Pager.NextPageTitle, "Next Page" },
                    { LocalizableStrings.Pager.PageLinkTitle, "Page {0}" },
                    { LocalizableStrings.Pager.PreviousPageTitle, "Previous Page" },
                    { LocalizableStrings.PageTitle.ActiveDiscussions, "Active Discussions" },
                    { LocalizableStrings.PageTitle.Default, "Forums" },
                    { LocalizableStrings.PageTitle.ForumSubscriptions, "Forum Subscriptions" },
                    { LocalizableStrings.PageTitle.MoveTopic, "Move Topic" },
                    { LocalizableStrings.PageTitle.PostEdit, "Edit Post" },
                    { LocalizableStrings.PageTitle.PostNew, "New Post" },
                    { LocalizableStrings.PageTitle.Search, "Search" },
                    { LocalizableStrings.PageTitle.TopicEdit, "Edit Topic" },
                    { LocalizableStrings.PageTitle.TopicNew, "New Topic" },
                    { LocalizableStrings.Posted, "Posted" },
                    { LocalizableStrings.PostLinkTitle, "Link to this post" },
                    { LocalizableStrings.Posts, "Posts" },
                    { LocalizableStrings.Priority, "Priority" },
                    { LocalizableStrings.PrivateMessages.PM, "PM" },
                    { LocalizableStrings.QuotePost, "Quote" },
                    { LocalizableStrings.Replies, "Replies" },
                    { LocalizableStrings.Reply, "Reply" },
                    { LocalizableStrings.RSS, "RSS" },
                    { LocalizableStrings.Search, "Search" },
                    { LocalizableStrings.Search_AdvancedSearch, "Advanced Search" },
                    { LocalizableStrings.Search_LimitResultsToPrevious, "Limit results to previous:" },
                    { LocalizableStrings.Search_SearchInForum, "Search in forum:" },
                    { LocalizableStrings.Search_SearchKeyword, "Search keyword:" },
                    { LocalizableStrings.Search_SearchWithin, "Search within:" },
                    { LocalizableStrings.SearchButton, "Search" },
                    { LocalizableStrings.SearchForumsTooltip, "Search Forums" },
                    { LocalizableStrings.SearchNoResultsText, "No posts were found that matched your criteria." },
                    { LocalizableStrings.SearchTermMinimumLengthIsNCharacters, "Search term minimum length is {0} characters." },
                    { LocalizableStrings.SelectTheForumToMoveTopic, "Select the forum you want to move the post to." },
                    { LocalizableStrings.Settings.ActiveDiscussionsFeedCount, "Active Discussions Feed Count" },
                    { LocalizableStrings.Settings.ActiveDiscussionsFeedEnabled, "Active Discussions Feed Enabled" },
                    { LocalizableStrings.Settings.ActiveDiscussionsPageSize, "Active Discussions Page Size" },
                    { LocalizableStrings.Settings.AllowPrivateMessages, "Allow Private Messages" },
                    { LocalizableStrings.Settings.AllowUsersToDeletePosts, "Allow Users To Delete Posts" },
                    { LocalizableStrings.Settings.AllowUsersToEditPosts, "Allow Users To Edit Posts" },
                    { LocalizableStrings.Settings.AllowUsersToManageSubscriptions, "Allow Users To Manage Forum Subscriptions" },
                    { LocalizableStrings.Settings.ForumEditor, "Forum Editor" },
                    { LocalizableStrings.Settings.ForumFeedCount, "Forum Feed Count" },
                    { LocalizableStrings.Settings.ForumFeedsEnabled, "Forum Feeds Enabled" },
                    { LocalizableStrings.Settings.ForumSearchTermMinimumLength, "Forum Search Term Min Length" },
                    { LocalizableStrings.Settings.ForumsEnabled, "Forums Enabled" },
                    { LocalizableStrings.Settings.ForumSubscriptionsPageSize, "Forum Subscriptions Page Size" },
                    { LocalizableStrings.Settings.HelpText.ActiveDiscussionsFeedCount, "The count of topics to include in the Active Discussion feed." },
                    { LocalizableStrings.Settings.HelpText.ActiveDiscussionsFeedEnabled, "Enables RSS feed for Active Discussions topics." },
                    { LocalizableStrings.Settings.HelpText.ActiveDiscussionsPageSize, "Set the page size for active discussions page e.g. '10' results per page." },
                    { LocalizableStrings.Settings.HelpText.AllowPrivateMessages, "Determines whether to allow private messages." },
                    { LocalizableStrings.Settings.HelpText.AllowUsersToDeletePosts, "A value indicating whether users are allowed to delete posts that they created." },
                    { LocalizableStrings.Settings.HelpText.AllowUsersToEditPosts, "A value indicating whether users are allowed to edit posts that they created." },
                    { LocalizableStrings.Settings.HelpText.AllowUsersToManageSubscriptions, "Check if you want to allow users to manage forum subscriptions" },
                    { LocalizableStrings.Settings.HelpText.ForumEditor, "Forum editor type. WARNING: not recommended to change in production environment." },
                    { LocalizableStrings.Settings.HelpText.ForumFeedCount, "The count of topics to include in the forum feed." },
                    { LocalizableStrings.Settings.HelpText.ForumFeedsEnabled, "Enables RSS feed for each forum." },
                    { LocalizableStrings.Settings.HelpText.ForumSearchTermMinimumLength, "Specify a min length for search term when searching forums." },
                    { LocalizableStrings.Settings.HelpText.ForumsEnabled, "Check to enable forums." },
                    { LocalizableStrings.Settings.HelpText.ForumSubscriptionsPageSize, "Set the page size for forum subscriptions e.g. '10' records per page." },
                    { LocalizableStrings.Settings.HelpText.HomePageActiveDiscussionsTopicCount, "The count of active topics to show on the home page." },
                    { LocalizableStrings.Settings.HelpText.LatestUserPostsPageSize, "Set the page size for latest posts for users e.g. '10' posts per page." },
                    { LocalizableStrings.Settings.HelpText.LayoutPathOverride, "Specify a different layout file for forums." },
                    { LocalizableStrings.Settings.HelpText.NotifyAboutPrivateMessages, "Indicates whether a customer should be notified about new private messages." },
                    { LocalizableStrings.Settings.HelpText.PMSubjectMaxLength, "Specify a max length for private message subject lines." },
                    { LocalizableStrings.Settings.HelpText.PMTextMaxLength, "Specify a max length for private message text." },
                    { LocalizableStrings.Settings.HelpText.PostMaxLength, "Specify a max length for posts." },
                    { LocalizableStrings.Settings.HelpText.PostsPageSize, "Set the page size for posts in topics e.g. '10' posts per page." },
                    { LocalizableStrings.Settings.HelpText.PrivateMessagesPageSize, "Set the page size for private messages e.g. '10' messages per page." },
                    { LocalizableStrings.Settings.HelpText.RelativeDateTimeFormattingEnabled, "Click to enable relative date and time formatting (e.g. 2 hours ago, a month ago)" },
                    { LocalizableStrings.Settings.HelpText.SearchResultsPageSize, "Set the page size for search results e.g. '10' results per page." },
                    { LocalizableStrings.Settings.HelpText.ShowAlertForPM, "Shows an alert for new Private Messages." },
                    { LocalizableStrings.Settings.HelpText.ShowUsersPostCount, "A value indicating whether to show users post count." },
                    { LocalizableStrings.Settings.HelpText.SignaturesEnabled, "Add an opportunity for users to specify signature. Signature will be displayed below each forum post." },
                    { LocalizableStrings.Settings.HelpText.StrippedTopicMaxLength, "Specify max length for a topic." },
                    { LocalizableStrings.Settings.HelpText.TopicsPageSize, "Set the page size for topics in forums e.g. '10' topics per page." },
                    { LocalizableStrings.Settings.HelpText.TopicSubjectMaxLength, "Specify max length for a topic subject." },
                    { LocalizableStrings.Settings.HomePageActiveDiscussionsTopicCount, "Home Page Active Discussions Topic Count" },
                    { LocalizableStrings.Settings.LatestUserPostsPageSize, "Latest User Posts Page Size" },
                    { LocalizableStrings.Settings.LayoutPathOverride, "Layout Path Override" },
                    { LocalizableStrings.Settings.NotifyAboutPrivateMessages, "Notify About Private Messages" },
                    { LocalizableStrings.Settings.PMSubjectMaxLength, "PM Subject Max Length" },
                    { LocalizableStrings.Settings.PMTextMaxLength, "PM Text Max Length" },
                    { LocalizableStrings.Settings.PostMaxLength, "Post Max Length" },
                    { LocalizableStrings.Settings.PostsPageSize, "Posts Page Size" },
                    { LocalizableStrings.Settings.PrivateMessagesPageSize, "Private Messages Page Size" },
                    { LocalizableStrings.Settings.RelativeDateTimeFormattingEnabled, "Relative Date & Time Formatting" },
                    { LocalizableStrings.Settings.SearchResultsPageSize, "Search Results Page Size" },
                    { LocalizableStrings.Settings.ShowAlertForPM, "Show Alert For PM" },
                    { LocalizableStrings.Settings.ShowUsersPostCount, "Show Users Post Count" },
                    { LocalizableStrings.Settings.SignaturesEnabled, "Signature Enabled" },
                    { LocalizableStrings.Settings.StrippedTopicMaxLength, "Stripped Topic Max Length" },
                    { LocalizableStrings.Settings.TopicsPageSize, "Topics Page Size" },
                    { LocalizableStrings.Settings.TopicSubjectMaxLength, "Topic Subject Max Length" },
                    { LocalizableStrings.Status, "Status" },
                    { LocalizableStrings.Topics, "Topics" },
                    { LocalizableStrings.Topics_GotoPostPager, "[Go to page: {0}]" },
                    { LocalizableStrings.TopicTitle, "Topic Title" },
                    { LocalizableStrings.TopicTypes.Announcement, "Announcement" },
                    { LocalizableStrings.TopicTypes.Normal, "Normal" },
                    { LocalizableStrings.TopicTypes.Sticky, "Sticky" },
                    { LocalizableStrings.TotalPosts, "Total Posts" },
                    { LocalizableStrings.UnwatchForum, "Unwatch Forum" },
                    { LocalizableStrings.UnwatchTopic, "Unwatch Topic" },
                    { LocalizableStrings.Views, "Views" },
                    { LocalizableStrings.WatchForum, "Watch Forum" },
                    { LocalizableStrings.WatchTopic, "Watch Topic" },
                };
            }
        }

        #endregion ILanguagePack Members
    }
}