using System.Collections.Generic;
using Kore.Localization;

namespace Kore.Web.Infrastructure
{
    public class LanguagePackInvariant : ILanguagePack
    {
        #region ILanguagePack Members

        public string CultureCode
        {
            get { return null; }
        }

        public IDictionary<string, string> LocalizedStrings
        {
            get
            {
                return new Dictionary<string, string>
                {
                    { KoreWebLocalizableStrings.General.Actions, "Actions" },
                    { KoreWebLocalizableStrings.General.Back, "Back" },
                    { KoreWebLocalizableStrings.General.Cancel, "Cancel" },
                    { KoreWebLocalizableStrings.General.Clear, "Clear" },
                    { KoreWebLocalizableStrings.General.Close, "Close" },
                    { KoreWebLocalizableStrings.General.Configuration, "Configuration" },
                    { KoreWebLocalizableStrings.General.Confirm, "Confirm" },
                    { KoreWebLocalizableStrings.General.ConfirmDeleteRecord, "Are you sure that you want to delete this record?" },
                    { KoreWebLocalizableStrings.General.Create, "Create" },
                    { KoreWebLocalizableStrings.General.CreateFormat, "Create {0}" },
                    { KoreWebLocalizableStrings.General.Delete, "Delete" },
                    { KoreWebLocalizableStrings.General.DeleteRecordError, "There was an error when deleting the record." },
                    { KoreWebLocalizableStrings.General.DeleteRecordErrorFormat, "There was an error when deleting the record. Additional information as follows: {0}" },
                    { KoreWebLocalizableStrings.General.DeleteRecordSuccess, "Successfully deleted record." },
                    { KoreWebLocalizableStrings.General.Details, "Details" },
                    { KoreWebLocalizableStrings.General.Download, "Download" },
                    { KoreWebLocalizableStrings.General.Edit, "Edit" },
                    { KoreWebLocalizableStrings.General.EditFormat, "Edit {0}" },
                    { KoreWebLocalizableStrings.General.Enabled, "Enabled" },
                    { KoreWebLocalizableStrings.General.Error, "Error" },
                    { KoreWebLocalizableStrings.General.Export, "Export" },
                    { KoreWebLocalizableStrings.General.GetRecordError, "There was an error when retrieving the record." },
                    { KoreWebLocalizableStrings.General.Home, "Home" },
                    { KoreWebLocalizableStrings.General.Import, "Import" },
                    { KoreWebLocalizableStrings.General.InsertRecordError, "There was an error when inserting the record." },
                    { KoreWebLocalizableStrings.General.InsertRecordSuccess, "Successfully inserted record." },
                    { KoreWebLocalizableStrings.General.Install, "Install" },
                    { KoreWebLocalizableStrings.General.Localize, "Localize" },
                    { KoreWebLocalizableStrings.General.Miscellaneous, "Miscellaneous" },
                    { KoreWebLocalizableStrings.General.Next, "Next" },
                    { KoreWebLocalizableStrings.General.None, "None" },
                    { KoreWebLocalizableStrings.General.OK, "OK" },
                    { KoreWebLocalizableStrings.General.OnOff, "On/Off" },
                    { KoreWebLocalizableStrings.General.Preview, "Preview" },
                    { KoreWebLocalizableStrings.General.Previous, "Previous" },
                    { KoreWebLocalizableStrings.General.Remove, "Remove" },
                    { KoreWebLocalizableStrings.General.Save, "Save" },
                    { KoreWebLocalizableStrings.General.SaveAndContinue, "Save & Continue" },
                    { KoreWebLocalizableStrings.General.Search, "Search" },
                    { KoreWebLocalizableStrings.General.Set, "Set" },
                    { KoreWebLocalizableStrings.General.SetDefault, "Set Default" },
                    { KoreWebLocalizableStrings.General.Settings, "Settings" },
                    { KoreWebLocalizableStrings.General.Submit, "Submit" },
                    { KoreWebLocalizableStrings.General.Success, "Success" },
                    { KoreWebLocalizableStrings.General.Themes, "Themes" },
                    { KoreWebLocalizableStrings.General.Toggle, "On/Off" },
                    { KoreWebLocalizableStrings.General.Uninstall, "Uninstall" },
                    { KoreWebLocalizableStrings.General.Unspecified, "Unspecified" },
                    { KoreWebLocalizableStrings.General.UpdateRecordError, "There was an error when updating the record." },
                    { KoreWebLocalizableStrings.General.UpdateRecordErrorFormat, "There was an error when updating the record. Additional information as follows: {0}" },
                    { KoreWebLocalizableStrings.General.UpdateRecordSuccess, "Successfully updated record." },
                    { KoreWebLocalizableStrings.General.Upload, "Upload" },
                    { KoreWebLocalizableStrings.General.View, "View" },
                    { KoreWebLocalizableStrings.General.ViewFormat, "View {0}" },
                    { KoreWebLocalizableStrings.Indexing.InvalidSearchQuery, "Invalid search query: {0}" },
                    { KoreWebLocalizableStrings.Indexing.NoSearchIndexToManage, "This site does not have a search index to manage." },
                    { KoreWebLocalizableStrings.Indexing.NoSearchIndexToRebuild, "There is no search index to rebuild." },
                    { KoreWebLocalizableStrings.Indexing.Rebuild, "Rebuild" },
                    { KoreWebLocalizableStrings.Indexing.RebuildForFreshStart, "Rebuild the search index for a fresh start:" },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexContainsNDocuments, "The search index contains {0} document/s." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexContainsNoFields, "The search index does not contain any fields." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexContainsTheseFields, "The search index contains the following fields: {0}." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexCurrentlyBeingRebuilt, "The index is currently being rebuilt." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexCurrentlyBeingUpdated, "The index is currently being updated." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexLastUpdatedOn, "The search index was last updated {0}." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexMayBeCorrupted, "The index might be corrupted. If you can't recover click on Rebuild." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexNoDocuments, "The search index does not contain any documents." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexNotBuiltYet, "The search index has not been built yet." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexRebuildFail, "The index, '{0}' could not be rebuilt. It might already be in use. Please try again later." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexRebuilt, "The index, '{0}' has been rebuilt." },
                    { KoreWebLocalizableStrings.Indexing.SearchIndexUpdated, "The search index has been updated." },
                    { KoreWebLocalizableStrings.Indexing.SearchMatchedNDocuments, "Your search for, '<strong>{0}</strong>' resulted in {1} documents." },
                    { KoreWebLocalizableStrings.Indexing.SearchMatchedNoDocuments, "Your search for, '<strong>{0}</strong>' did not match any documents." },
                    { KoreWebLocalizableStrings.Indexing.Title, "Search Index" },
                    { KoreWebLocalizableStrings.Localization.ResetLocalizableStringsError, "There was an error when resetting the localized strings." },
                    { KoreWebLocalizableStrings.Localization.ResetLocalizableStringsSuccess, "Successfully reset the localized strings." },
                    { KoreWebLocalizableStrings.Log.ClearConfirm, "Are you sure you want to clear the log?" },
                    { KoreWebLocalizableStrings.Log.ClearError, "Error when trying to clear the log." },
                    { KoreWebLocalizableStrings.Log.ClearSuccess, "Successfully cleared the log." },
                    { KoreWebLocalizableStrings.Log.Title, "Log" },
                    { KoreWebLocalizableStrings.Log.Model.ErrorClass, "Error Class" },
                    { KoreWebLocalizableStrings.Log.Model.ErrorMessage, "Error Message" },
                    { KoreWebLocalizableStrings.Log.Model.ErrorMethod, "Error Method" },
                    { KoreWebLocalizableStrings.Log.Model.ErrorSource, "Error Source" },
                    { KoreWebLocalizableStrings.Log.Model.EventDateTime, "Event Date/Time" },
                    { KoreWebLocalizableStrings.Log.Model.EventLevel, "Event Level" },
                    { KoreWebLocalizableStrings.Log.Model.EventMessage, "Event Message" },
                    { KoreWebLocalizableStrings.Log.Model.InnerErrorMessage, "Inner Error Message" },
                    { KoreWebLocalizableStrings.Log.Model.MachineName, "Machine Name" },
                    { KoreWebLocalizableStrings.Log.Model.UserName, "Username" },
                    { KoreWebLocalizableStrings.Maintenance.Title, "Maintenance" },
                    { KoreWebLocalizableStrings.Membership.AllRolesSelectListOption, "[All Roles]" },
                    { KoreWebLocalizableStrings.Membership.ChangePassword, "Change Password" },
                    { KoreWebLocalizableStrings.Membership.ChangePasswordError, "There was an error when changing the password." },
                    { KoreWebLocalizableStrings.Membership.ChangePasswordModel.ConfirmPassword, "Confirm Password" },
                    { KoreWebLocalizableStrings.Membership.ChangePasswordModel.Password, "Password" },
                    { KoreWebLocalizableStrings.Membership.ChangePasswordModel.UserName, "Username" },
                    { KoreWebLocalizableStrings.Membership.ChangePasswordSuccess, "Successfully changed password." },
                    { KoreWebLocalizableStrings.Membership.EditRolePermissions, "Edit Role Permissions" },
                    { KoreWebLocalizableStrings.Membership.InsertUserError, "There was an error when trying to create the user." },
                    { KoreWebLocalizableStrings.Membership.InvalidEmailAddress, "That is not a valid e-mail address. Please check your input and try again." },
                    { KoreWebLocalizableStrings.Membership.IsLockedOut, "Is Locked Out" },
                    { KoreWebLocalizableStrings.Membership.Password, "Password" },
                    { KoreWebLocalizableStrings.Membership.PermissionModel.Category, "Category" },
                    { KoreWebLocalizableStrings.Membership.PermissionModel.Name, "Name" },
                    { KoreWebLocalizableStrings.Membership.Permissions, "Permissions" },
                    { KoreWebLocalizableStrings.Membership.RoleModel.Name, "Name" },
                    { KoreWebLocalizableStrings.Membership.Roles, "Roles" },
                    { KoreWebLocalizableStrings.Membership.SavePermissionsError, "There was an error when saving permissions." },
                    { KoreWebLocalizableStrings.Membership.SavePermissionsSuccess, "Successfully saved permissions." },
                    { KoreWebLocalizableStrings.Membership.SaveRolesError, "There was an error when saving roles." },
                    { KoreWebLocalizableStrings.Membership.SaveRolesSuccess, "Successfully saved roles." },
                    { KoreWebLocalizableStrings.Membership.Title, "Membership" },
                    { KoreWebLocalizableStrings.Membership.UpdateUserRoles, "Update User Roles" },
                    { KoreWebLocalizableStrings.Membership.UserEmailAlreadyExists, "A user with that e-mail address already exists. If you are the owner of that e-mail address, please login and try again." },
                    { KoreWebLocalizableStrings.Membership.UserModel.Email, "Email" },
                    { KoreWebLocalizableStrings.Membership.UserModel.IsActive, "Is Active" },
                    { KoreWebLocalizableStrings.Membership.UserModel.IsLockedOut, "Is Locked Out" },
                    { KoreWebLocalizableStrings.Membership.UserModel.Roles, "Roles" },
                    { KoreWebLocalizableStrings.Membership.UserModel.UserName, "Username" },
                    { KoreWebLocalizableStrings.Membership.Users, "Users" },
                    { KoreWebLocalizableStrings.Plugins.InstallPluginError, "There was an error when installing the plugin." },
                    { KoreWebLocalizableStrings.Plugins.InstallPluginSuccess, "Successfully installed plugin." },
                    { KoreWebLocalizableStrings.Plugins.ManagePlugins, "Manage Plugins" },
                    { KoreWebLocalizableStrings.Plugins.Title, "Plugins" },
                    { KoreWebLocalizableStrings.Plugins.Model.Group, "Group" },
                    { KoreWebLocalizableStrings.Plugins.Model.PluginInfo, "Plugin Info" },
                    { KoreWebLocalizableStrings.Plugins.UninstallPluginError, "There was an error when uninstalling the plugin." },
                    { KoreWebLocalizableStrings.Plugins.UninstallPluginSuccess, "Successfully uninstalled plugin." },
                    { KoreWebLocalizableStrings.ScheduledTasks.ExecutedTaskError, "There was an error when executing the task." },
                    { KoreWebLocalizableStrings.ScheduledTasks.ExecutedTaskSuccess, "Successfully executed task." },
                    { KoreWebLocalizableStrings.ScheduledTasks.ManageScheduledTasks, "Manage Scheduled Tasks" },
                    { KoreWebLocalizableStrings.ScheduledTasks.RunNow, "Run Now" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Model.Enabled, "Is Enabled" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Model.LastEndUtc, "Last End (UTC)" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Model.LastStartUtc, "Last Start (UTC)" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Model.LastSuccessUtc, "Last Success (UTC)" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Model.Name, "Name" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Model.Seconds, "Seconds" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Model.StopOnError, "Stop On Error" },
                    { KoreWebLocalizableStrings.ScheduledTasks.Title, "Scheduled Tasks" },
                    { KoreWebLocalizableStrings.Settings.Captcha.PrivateKey, "Private Key" },
                    { KoreWebLocalizableStrings.Settings.Captcha.PublicKey, "Public Key" },
                    { KoreWebLocalizableStrings.Settings.Captcha.Theme, "Theme" },
                    { KoreWebLocalizableStrings.Settings.Membership.GeneratedPasswordLength, "Length" },
                    { KoreWebLocalizableStrings.Settings.Membership.GeneratedPasswordNumberOfNonAlphanumericChars, "# Non-Alphanumeric Characters" },
                    { KoreWebLocalizableStrings.Settings.Model.Name, "Name" },
                    { KoreWebLocalizableStrings.Settings.Site.AdminLayoutPath, "Admin Layout Path" },
                    { KoreWebLocalizableStrings.Settings.Site.AllowUserToSelectTheme, "Allow User To Select Theme" },
                    { KoreWebLocalizableStrings.Settings.Site.DefaultDesktopTheme, "Default Desktop Theme" },
                    { KoreWebLocalizableStrings.Settings.Site.DefaultFrontendLayoutPath, "Default Frontend Layout Path" },
                    { KoreWebLocalizableStrings.Settings.Site.DefaultGridPageSize, "Default Grid Page Size" },
                    { KoreWebLocalizableStrings.Settings.Site.DefaultLanguage, "Default Language" },
                    { KoreWebLocalizableStrings.Settings.Site.DefaultMetaDescription, "Default Meta Description" },
                    { KoreWebLocalizableStrings.Settings.Site.DefaultMetaKeywords, "Default Meta Keywords" },
                    { KoreWebLocalizableStrings.Settings.Site.DefaultMobileTheme, "Default Mobile Theme" },
                    { KoreWebLocalizableStrings.Settings.Site.HomePageTitle, "Home Page Title" },
                    { KoreWebLocalizableStrings.Settings.Site.SiteName, "Site Name" },
                    { KoreWebLocalizableStrings.Settings.Site.Tabs.General, "General" },
                    { KoreWebLocalizableStrings.Settings.Site.Tabs.Localization, "Localization" },
                    { KoreWebLocalizableStrings.Settings.Site.Tabs.SEO, "SEO" },
                    { KoreWebLocalizableStrings.Settings.Site.Tabs.Themes, "Themes" },
                    { KoreWebLocalizableStrings.Settings.Smtp.DisplayName, "Display Name" },
                    { KoreWebLocalizableStrings.Settings.Smtp.EnableSsl, "Enable SSL" },
                    { KoreWebLocalizableStrings.Settings.Smtp.Host, "Host" },
                    { KoreWebLocalizableStrings.Settings.Smtp.MaxTries, "Max Tries" },
                    { KoreWebLocalizableStrings.Settings.Smtp.MessagesPerBatch, "Messages Per Batch" },
                    { KoreWebLocalizableStrings.Settings.Smtp.Password, "Password" },
                    { KoreWebLocalizableStrings.Settings.Smtp.Port, "Port" },
                    { KoreWebLocalizableStrings.Settings.Smtp.UseDefaultCredentials, "Use Default Credentials" },
                    { KoreWebLocalizableStrings.Settings.Smtp.Username, "Username" },
                    { KoreWebLocalizableStrings.Themes.Model.IsDefaultDesktopTheme, "Default Desktop Theme" },
                    { KoreWebLocalizableStrings.Themes.Model.IsDefaultMobileTheme, "Default Mobile Theme" },
                    { KoreWebLocalizableStrings.Themes.Model.MobileTheme, "For Mobile?" },
                    { KoreWebLocalizableStrings.Themes.Model.PreviewImageUrl, "Preview" },
                    { KoreWebLocalizableStrings.Themes.Model.SupportRtl, "Supports RTL" },
                    { KoreWebLocalizableStrings.Themes.SetDesktopThemeError, "Error when setting default desktop theme." },
                    { KoreWebLocalizableStrings.Themes.SetDesktopThemeSuccess, "Successfully set default desktop theme." },
                    { KoreWebLocalizableStrings.Themes.SetMobileThemeError, "Error when setting default mobile theme." },
                    { KoreWebLocalizableStrings.Themes.SetMobileThemeSuccess, "Successfully set default mobile theme." },
                    { KoreWebLocalizableStrings.UserProfile.Account.FamilyName, "Family Name" },
                    { KoreWebLocalizableStrings.UserProfile.Account.GivenNames, "Given Name/s" },
                    { KoreWebLocalizableStrings.UserProfile.Account.ShowFamilyNameFirst, "Show Family Name First" },
                    { KoreWebLocalizableStrings.UserProfile.Localization.PreferredLanguage, "Preferred Language" },
                    { KoreWebLocalizableStrings.UserProfile.Mobile.DontUseMobileVersion, "Don't Use Mobile Version" },
                    { KoreWebLocalizableStrings.UserProfile.Theme.PreferredTheme, "Preferred Theme" },
                    { KoreWebLocalizableStrings.Validation.Date, "Please enter a valid date." },
                    { KoreWebLocalizableStrings.Validation.Digits, "Please enter only digits." },
                    { KoreWebLocalizableStrings.Validation.Email, "Please enter a valid email address." },
                    { KoreWebLocalizableStrings.Validation.EqualTo, "Please enter the same value again." },
                    { KoreWebLocalizableStrings.Validation.MaxLength, "Please enter no more than {0} characters." },
                    { KoreWebLocalizableStrings.Validation.MinLength, "Please enter at least {0} characters." },
                    { KoreWebLocalizableStrings.Validation.Number, "Please enter a valid number." },
                    { KoreWebLocalizableStrings.Validation.Range, "Please enter a value between {0} and {1}." },
                    { KoreWebLocalizableStrings.Validation.RangeLength, "Please enter a value between {0} and {1} characters long." },
                    { KoreWebLocalizableStrings.Validation.RangeMax, "Please enter a value less than or equal to {0}." },
                    { KoreWebLocalizableStrings.Validation.RangeMin, "Please enter a value greater than or equal to {0}." },
                    { KoreWebLocalizableStrings.Validation.Required, "This field is required." },
                    { KoreWebLocalizableStrings.Validation.Url, "Please enter a valid URL." },
                };
            }
        }

        #endregion ILanguagePack Members
    }
}