using System.Collections.Generic;
using Kore.Localization;

namespace Kore.Plugins.Widgets.RevolutionSlider.Infrastructure
{
    public class LanguagePackInvariant : ILanguagePack
    {
        #region ILanguagePack Members

        public string CultureCode
        {
            get { return null; }
        }

        public IDictionary<string, string> LocalizedStrings
        {
            get
            {
                return new Dictionary<string, string>
                {
                    { LocalizableStrings.Layers, "Layers" },
                    { LocalizableStrings.RevolutionSlider, "Revolution Slider" },
                    { LocalizableStrings.Sliders, "Sliders" },
                    { LocalizableStrings.Slides, "Slides" },
                    { LocalizableStrings.Models.Layer.Tabs.General, "General" },
                    { LocalizableStrings.Models.Layer.Tabs.Video, "Video" },
                    { LocalizableStrings.Models.Layer.AspectRatio, "Aspect Ratio" },
                    { LocalizableStrings.Models.Layer.AutoPlay, "Auto Play" },
                    { LocalizableStrings.Models.Layer.AutoPlayOnlyFirstTime, "Auto Play: Only First Time" },
                    { LocalizableStrings.Models.Layer.CaptionText, "Caption Text" },
                    { LocalizableStrings.Models.Layer.Easing, "Easing" },
                    { LocalizableStrings.Models.Layer.ElementDelay, "Element Delay" },
                    { LocalizableStrings.Models.Layer.End, "End" },
                    { LocalizableStrings.Models.Layer.EndEasing, "End Easing" },
                    { LocalizableStrings.Models.Layer.EndElementDelay, "End Element Delay" },
                    { LocalizableStrings.Models.Layer.EndSpeed, "End Speed" },
                    { LocalizableStrings.Models.Layer.ForceCover, "Force Cover" },
                    { LocalizableStrings.Models.Layer.ForceRewind, "Force Rewind" },
                    { LocalizableStrings.Models.Layer.HorizontalOffset, "Horizontal Offset" },
                    { LocalizableStrings.Models.Layer.IncomingAnimation, "Incoming Animation" },
                    { LocalizableStrings.Models.Layer.Mute, "Mute" },
                    { LocalizableStrings.Models.Layer.NextSlideAtEnd, "Next Slide At End" },
                    { LocalizableStrings.Models.Layer.OutgoingAnimation, "Outgoing Animation" },
                    { LocalizableStrings.Models.Layer.ShowVideoControls, "Show Video Controls" },
                    { LocalizableStrings.Models.Layer.Speed, "Speed" },
                    { LocalizableStrings.Models.Layer.SplitIn, "Split In" },
                    { LocalizableStrings.Models.Layer.SplitOut, "Split Out" },
                    { LocalizableStrings.Models.Layer.Start, "Start" },
                    { LocalizableStrings.Models.Layer.StyleClass, "CSS Class" },
                    { LocalizableStrings.Models.Layer.VerticalOffset, "Vertical Offset" },
                    { LocalizableStrings.Models.Layer.VideoAttributes, "Video Attributes" },
                    { LocalizableStrings.Models.Layer.VideoHeight, "Height" },
                    { LocalizableStrings.Models.Layer.VideoHeightUnit, "Height Unit" },
                    { LocalizableStrings.Models.Layer.VideoLoop, "Loop" },
                    { LocalizableStrings.Models.Layer.VideoMp4, "MP4 URL" },
                    { LocalizableStrings.Models.Layer.VideoOgv, "OGV URL" },
                    { LocalizableStrings.Models.Layer.VideoPoster, "Poster URL" },
                    { LocalizableStrings.Models.Layer.VideoPreload, "Preload" },
                    { LocalizableStrings.Models.Layer.VideoType, "Video Type" },
                    { LocalizableStrings.Models.Layer.VideoWebM, "WebM URL" },
                    { LocalizableStrings.Models.Layer.VideoWidth, "Width" },
                    { LocalizableStrings.Models.Layer.VideoWidthUnit, "Width Unit" },
                    { LocalizableStrings.Models.Layer.VimeoId, "Vimeo ID" },
                    { LocalizableStrings.Models.Layer.X, "X" },
                    { LocalizableStrings.Models.Layer.Y, "Y" },
                    { LocalizableStrings.Models.Layer.YouTubeId, "YouTube ID" },
                    { LocalizableStrings.Models.Layer.HelpText.AutoPlay, "Will play the Video Directly when slider has been loaded." },
                    { LocalizableStrings.Models.Layer.HelpText.AutoPlayOnlyFirstTime, "After first Autplay the video will not be played automatically." },
                    { LocalizableStrings.Models.Layer.HelpText.Easing, "The Easing Art how the caption is moved in to the slide (note! Animation art set via Classes!)." },
                    { LocalizableStrings.Models.Layer.HelpText.ElementDelay, "A Value between 0 and 1 like 0.1 to make delays between the Splitted Text Element (start) Animations. Higher the amount of words or chars, you should decrease that number!" },
                    { LocalizableStrings.Models.Layer.HelpText.End, "The timepoint in millisecond when/at the Caption should move out from the slide." },
                    { LocalizableStrings.Models.Layer.HelpText.EndEasing, "The Easing Art how the caption is moved out from the slide (note! Animation art set via Classes!)." },
                    { LocalizableStrings.Models.Layer.HelpText.EndElementDelay, "A Value between 0 and 1 like 0.1 to make delays between the Splitted Text Element (end) Animations. Higher the amount of words or chars, you should decrease that number!" },
                    { LocalizableStrings.Models.Layer.HelpText.EndSpeed, "The speed in milliseconds of the transition to move the Caption out from the Slide at the defined timepoint." },
                    { LocalizableStrings.Models.Layer.HelpText.ForceCover, "Used only at HTML5 Videos. In case it is selected, the Videos will be resized to cover the full Slider size." },
                    { LocalizableStrings.Models.Layer.HelpText.ForceRewind, "Every time the Slide is shown, the Video will rewind to the start." },
                    { LocalizableStrings.Models.Layer.HelpText.HorizontalOffset, "Only works if data-x set to left/center/right. It will move the Caption with the defined \"px\" from the aligned position. i.e. data-x=\"center\" data-hoffset=\"-100\" will put the caption 100px left from the slide center horizontaly." },
                    { LocalizableStrings.Models.Layer.HelpText.IncomingAnimation, "Defines the start animation on Captions." },
                    { LocalizableStrings.Models.Layer.HelpText.NextSlideAtEnd, "After video come to the end position, it swaps to the next slide automatically." },
                    { LocalizableStrings.Models.Layer.HelpText.OutgoingAnimation, "Defines the end animation on Captions." },
                    { LocalizableStrings.Models.Layer.HelpText.ShowVideoControls, "Show/Hide the controls of the Video." },
                    { LocalizableStrings.Models.Layer.HelpText.Speed, "The speed in milliseconds of the transition to move the Caption in the Slide at the defined timepoint." },
                    { LocalizableStrings.Models.Layer.HelpText.SplitIn, "Split Text Animation (incoming transition) to 'words', 'chars' or 'lines'. This will create amazing Animation Effects on one go, without the needs to create more captions." },
                    { LocalizableStrings.Models.Layer.HelpText.SplitOut, "Split Text Animation (outgoing transition) to 'words', 'chars' or 'lines'. Only available if data-end is set!" },
                    { LocalizableStrings.Models.Layer.HelpText.Start, "The timepoint in millisecond when/at the Caption should move in to the slide." },
                    { LocalizableStrings.Models.Layer.HelpText.StyleClass, "(like 'big_white', 'big_orange', 'medium_grey' etc...). These are Styling classes created in the settings.css  You can add unlimited amount of Styles in your own css file, to style your captions at the top level already.<" },
                    { LocalizableStrings.Models.Layer.HelpText.VerticalOffset, "Only works if data-y set to top/center/bottom. It will move the Caption with the defined \"px\" from the aligned position. i.e. data-x=\"center\" data-hoffset=\"-100\" will put the caption 100px left from the slide center vertically." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoAttributes, "Further Video Attributes for not listed Options and Settings of Video. Used for YouTube and Vimeo like 'enablejsapi=1&html5=1&hd=1&wmode=opaque&showinfo=0&rel=0'." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoHeight, "Height of Video (i.e. 500 for 500px, or 100% for 100%)" },
                    { LocalizableStrings.Models.Layer.HelpText.VideoLoop, "Loop HTML5 Videos - 'none', 'loop', 'loopandnoslidestop' loop and no slide stop will loop the video, but as soon the video Timer reached the endpoint, next slide will be started." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoMp4, "The MP4 Source for the HTML5 Video." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoOgv, "The OGV Source for the HTML5 Video." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoPoster, "The full path to an image which will be shown as Thumbnail for the Video. (only if autoplay set to false, or autoplayonlyfirsttime set to true)." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoPreload, "Which content of Video should be preloaded. 'none', 'meta', 'auto'." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoWebM, "The WEBM Source for the HTML5 Video." },
                    { LocalizableStrings.Models.Layer.HelpText.VideoWidth, "Width of Video (i.e. 500 for 500px, or 100% for 100%)" },
                    { LocalizableStrings.Models.Layer.HelpText.VimeoId, "The Vimeo ID of the Video." },
                    { LocalizableStrings.Models.Layer.HelpText.YouTubeId, "The YouTube ID of the Video." },

                    { LocalizableStrings.Models.Slide.BackgroundFit, "Background Fit" },
                    { LocalizableStrings.Models.Slide.BackgroundFitCustomValue, "Background Fit: Custom Value" },
                    { LocalizableStrings.Models.Slide.BackgroundFitEnd, "Background Fit End" },
                    { LocalizableStrings.Models.Slide.BackgroundPosition, "Background Position" },
                    { LocalizableStrings.Models.Slide.BackgroundPositionEnd, "Background Position End" },
                    { LocalizableStrings.Models.Slide.BackgroundRepeat, "Background Repeat" },
                    { LocalizableStrings.Models.Slide.Delay, "Delay" },
                    { LocalizableStrings.Models.Slide.Duration, "Duration" },
                    { LocalizableStrings.Models.Slide.Easing, "Easing" },
                    { LocalizableStrings.Models.Slide.ImageUrl, "Image URL" },
                    { LocalizableStrings.Models.Slide.KenBurnsEffect, "Ken Burns Effect" },
                    { LocalizableStrings.Models.Slide.LazyLoad, "Lazy Load" },
                    { LocalizableStrings.Models.Slide.Link, "Link" },
                    { LocalizableStrings.Models.Slide.MasterSpeed, "Master Speed" },
                    { LocalizableStrings.Models.Slide.Order, "Order" },
                    { LocalizableStrings.Models.Slide.RandomTransition, "Random Transition" },
                    { LocalizableStrings.Models.Slide.SlideIndex, "Slide Index" },
                    { LocalizableStrings.Models.Slide.SliderId, "Slider" },
                    { LocalizableStrings.Models.Slide.SlotAmount, "Slot Amount" },
                    { LocalizableStrings.Models.Slide.Target, "Target" },
                    { LocalizableStrings.Models.Slide.Thumb, "Thumb" },
                    { LocalizableStrings.Models.Slide.Title, "Title" },
                    { LocalizableStrings.Models.Slide.Transition, "Transition" },
                    { LocalizableStrings.Models.Slide.HelpText.BackgroundFit, "data-bgfit:cover / contain / normal / width(%) height(%). (Select one to decide how the image should fit in the Slide Main Container). For Ken Burn use only a Number, which is the % Zoom at start. 100 will fit with Width or height automatically, 200 will be double sized etc.." },
                    { LocalizableStrings.Models.Slide.HelpText.BackgroundFitEnd, "Use only a Number. i.e. 300 will be a 300% Zoomed image where the basic 100% is fitting with width or height." },
                    { LocalizableStrings.Models.Slide.HelpText.BackgroundPositionEnd, "For Ken Burns Animation. This is where the IMG will be animated." },
                    { LocalizableStrings.Models.Slide.HelpText.BackgroundRepeat, "The way the image is shown in the slide main container." },
                    { LocalizableStrings.Models.Slide.HelpText.Delay, "A new Dealy value for the Slide. If no delay defined per slide, the dealy defined via Options will be used." },
                    { LocalizableStrings.Models.Slide.HelpText.Duration, "Duration for Ken Burns. The value in ms how long the animation of ken burns effect should go. i.e. 3000 will make a 3s zoom and movement." },
                    { LocalizableStrings.Models.Slide.HelpText.Easing, "Easing of Ken Burns Effect." },
                    { LocalizableStrings.Models.Slide.HelpText.KenBurnsEffect, "Turn on Ken Burns Effect or keep it disabled" },
                    { LocalizableStrings.Models.Slide.HelpText.Link, "A link on the whole slide pic." },
                    { LocalizableStrings.Models.Slide.HelpText.MasterSpeed, "The speed of the transition in \"ms\". Default value is 300 (0.3 sec)." },
                    { LocalizableStrings.Models.Slide.HelpText.RandomTransition, "This will allow a Random transitions of the Selected Transitions you choosed in the data-transitions. Don't use together with random premium and random flat transitions!" },
                    { LocalizableStrings.Models.Slide.HelpText.SlideIndex, "Possible values:  next,back, 1-x (where x is the max. Amount of slide). If this value is set, click on slide will call the next / previous, or  n th Slide." },
                    { LocalizableStrings.Models.Slide.HelpText.SlotAmount, "The number of slots or boxes the slide is divided into. If you use boxfade, over 7 slots can be juggy." },
                    { LocalizableStrings.Models.Slide.HelpText.Target, "The target of the Link for the whole slide pic. (i.e. \"_blank\", \"_self\")." },
                    { LocalizableStrings.Models.Slide.HelpText.Thumb, "An Alternative Source for thumbs. If not defined a copy of the background image will be used in resized form." },
                    { LocalizableStrings.Models.Slide.HelpText.Title, "In Navigation Style Preview1-Preview4 mode you can show the Title of the Slides also. Due this option you can define for each slide its own Title." },
                    { LocalizableStrings.Models.Slide.HelpText.Transition, "The appearance transition of this slide. You can define more than one, so in each loop the next slide transition type will be shown." },

                    { LocalizableStrings.Models.Slider.Name, "Name" },

                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.General, "General" },
                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.Navigation, "Navigation" },
                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.Loops, "Loops" },
                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.MobileVisibility, "Mobile Visibility" },
                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.LayoutStyles, "Layout Styles" },
                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.Parallax, "Parallax" },
                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.PanZoom, "Pan Zoom" },
                    { LocalizableStrings.RevolutionSliderBlock.EditorTabs.Other, "Other" },
                    { LocalizableStrings.RevolutionSliderBlock.SliderId, "Slider" },
                    { LocalizableStrings.RevolutionSliderBlock.ControlId, "Control ID" },
                    { LocalizableStrings.RevolutionSliderBlock.Delay, "Delay" },
                    { LocalizableStrings.RevolutionSliderBlock.StartHeight, "Start Height" },
                    { LocalizableStrings.RevolutionSliderBlock.StartWidth, "Start Width" },
                    { LocalizableStrings.RevolutionSliderBlock.Shuffle, "Shuffle" },
                    { LocalizableStrings.RevolutionSliderBlock.KeyboardNavigation, "Keyboard Navigation" },
                    { LocalizableStrings.RevolutionSliderBlock.OnHoverStop, "On Hover Stop" },
                    { LocalizableStrings.RevolutionSliderBlock.ThumbWidth, "Thumb Width" },
                    { LocalizableStrings.RevolutionSliderBlock.ThumbHeight, "Thumb Height" },
                    { LocalizableStrings.RevolutionSliderBlock.ThumbAmount, "Thumb Amount" },
                    { LocalizableStrings.RevolutionSliderBlock.HideThumbs, "Hide Thumbs" },
                    { LocalizableStrings.RevolutionSliderBlock.NavigationType, "Navigation Type" },
                    { LocalizableStrings.RevolutionSliderBlock.NavigationArrows, "Navigation Arrows" },
                    { LocalizableStrings.RevolutionSliderBlock.NavigationStyle, "Navigation Style" },
                    { LocalizableStrings.RevolutionSliderBlock.NavigationHAlign, "Navigation H-Align" },
                    { LocalizableStrings.RevolutionSliderBlock.NavigationVAlign, "Navigation V-Align" },
                    { LocalizableStrings.RevolutionSliderBlock.NavigationHOffset, "Navigation H-Offset" },
                    { LocalizableStrings.RevolutionSliderBlock.NavigationVOffset, "Navigation V-Offset" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowLeftHAlign, "Solo Arrow Left H-Align" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowRightHAlign, "Solo Arrow Right H-Align" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowLeftVAlign, "Solo Arrow Left V-Align" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowRightVAlign, "Solo Arrow Right V-Align" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowLeftHOffset, "Solo Arrow Left H-Offset" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowRightHOffset, "Solo Arrow Right H-Offset" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowLeftVOffset, "Solo Arrow Left V-Offset" },
                    { LocalizableStrings.RevolutionSliderBlock.SoloArrowRightVOffset, "Solo Arrow Right V-Offset" },
                    { LocalizableStrings.RevolutionSliderBlock.TouchEnabled, "Touch Enabled" },
                    { LocalizableStrings.RevolutionSliderBlock.SwipeVelocity, "Swipe Velocity" },
                    { LocalizableStrings.RevolutionSliderBlock.SwipeMaxTouches, "Swipe Max Touches" },
                    { LocalizableStrings.RevolutionSliderBlock.SwipeMinTouches, "Swipe Min Touches" },
                    { LocalizableStrings.RevolutionSliderBlock.DragBlockVertical, "Drag Block Vertical" },
                    { LocalizableStrings.RevolutionSliderBlock.StartWithSlide, "Start with Slide" },
                    { LocalizableStrings.RevolutionSliderBlock.StopAtSlide, "Stop at Slide" },
                    { LocalizableStrings.RevolutionSliderBlock.StopAfterLoops, "Stop After Loops" },
                    { LocalizableStrings.RevolutionSliderBlock.HideCaptionAtLimit, "Hide Caption at Limit" },
                    { LocalizableStrings.RevolutionSliderBlock.HideAllCaptionAtLimit, "Hide All Captions at Limit" },
                    { LocalizableStrings.RevolutionSliderBlock.HideSliderAtLimit, "Hide Slider at Limit" },
                    { LocalizableStrings.RevolutionSliderBlock.HideNavDelayOnMobile, "Hide Nav Delay on Mobile" },
                    { LocalizableStrings.RevolutionSliderBlock.HideThumbsOnMobile, "Hide Thumbs on Mobile" },
                    { LocalizableStrings.RevolutionSliderBlock.HideBulletsOnMobile, "Hide Bullets on Mobile" },
                    { LocalizableStrings.RevolutionSliderBlock.HideArrowsOnMobile, "Hide Arrows on Mobile" },
                    { LocalizableStrings.RevolutionSliderBlock.HideThumbsUnderResolution, "Hide Thumbs under Resolution" },
                    { LocalizableStrings.RevolutionSliderBlock.Spinner, "Spinner" },
                    { LocalizableStrings.RevolutionSliderBlock.HideTimerBar, "Hide Timer Bar" },
                    { LocalizableStrings.RevolutionSliderBlock.FullWidth, "Full Width" },
                    { LocalizableStrings.RevolutionSliderBlock.AutoHeight, "Auto Height" },
                    { LocalizableStrings.RevolutionSliderBlock.MinHeight, "Min Height" },
                    { LocalizableStrings.RevolutionSliderBlock.FullScreenAlignForce, "Full Screen Align Force" },
                    { LocalizableStrings.RevolutionSliderBlock.ForceFullWidth, "Force Full Width" },
                    { LocalizableStrings.RevolutionSliderBlock.FullScreen, "Full Screen" },
                    { LocalizableStrings.RevolutionSliderBlock.FullScreenOffsetContainer, "Full Screen Offset Container" },
                    { LocalizableStrings.RevolutionSliderBlock.FullScreenOffset, "Full Screen Offset" },
                    { LocalizableStrings.RevolutionSliderBlock.FullScreenOffsetUnit, "Full Screen Offset Unit" },
                    { LocalizableStrings.RevolutionSliderBlock.Shadow, "Shadow" },
                    { LocalizableStrings.RevolutionSliderBlock.DottedOverlay, "Dotted Overlay" },
                    { LocalizableStrings.RevolutionSliderBlock.Parallax, "Parallax" },
                    { LocalizableStrings.RevolutionSliderBlock.ParallaxBgFreeze, "Parallax Background Freeze" },
                    { LocalizableStrings.RevolutionSliderBlock.ParallaxLevels, "Parallax Levels" },
                    { LocalizableStrings.RevolutionSliderBlock.ParallaxDisableOnMobile, "Parallax Disable on Mobile" },
                    { LocalizableStrings.RevolutionSliderBlock.PanZoomDisableOnMobile, "Pan Zoom Disable on Mobile" },
                    { LocalizableStrings.RevolutionSliderBlock.SimplifyAll, "Simplify All" },
                    
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.Delay, "The time one slide stays on the screen in Milliseconds. Global Setting. You can set per Slide extra local delay time via the data-delay in the &lt;li&gt; element (Default: 9000)." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.StartHeight, "This Height of the Grid where the Captions are displayed in Pixel. This Height is the Max height of Slider in Fullwidth Layout and in Responsive Layout. In Fullscreen Layout the Gird will be centered Vertically in case the Slider is higher then this value." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.StartWidth, "This Height of the Grid where the Captions are displayed in Pixel. This Width is the Max Width of Slider in Responsive Layout.  In Fullscreen and in FullWidth Layout the Gird will be centered Horizontally in case the Slider is wider then this value." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.KeyboardNavigation, "Allows to use the Left/Right Arrow for Keyboard navigation when Slider is in Focus." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.OnHoverStop, "Stop the Timer if mouse is hovering the Slider. Caption animations are not stopped!! They will just play to the end." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.ThumbWidth, "The width of the thumbs in pixels. Thumbs are not responsive from basic. For Responsive Thumbs you will need to create media query based thumb sizes." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.ThumbHeight, "The height of the thumbs in pixels. Thumbs are not responsive from basic. For Responsive Thumbs you will need to create media query based thumb sizes." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.ThumbAmount, "The Amount of visible Thumbs in the same time. The rest of the thumbs are only visible on hover, or at slide change." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideThumbs, "0 - Never hide Thumbs.  1000- 100000 (ms) hide thumbs and navigation arrows, bullets after the predefined ms (1000ms == 1 sec,  1500 == 1,5 sec etc..)" },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.NavigationType, "Display type of the 'bullet/thumbnail' bar." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.NavigationArrows, "Display position of the Navigation Arrows." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.NavigationStyle, "Look of the navigation bullets if navigationType 'bullet' selected." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.NavigationHAlign, "Horizontal Align of the Navigation bullets / thumbs (depending on which Style has been selected)." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.NavigationVAlign, "Vertical Align of the Navigation bullets / thumbs (depending on which Style has been selected)." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.NavigationHOffset, "The Offset position of the navigation depending on the aligned position. From -1000 to +1000 any value in px. i.e. -30." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.NavigationVOffset, "The Offset position of the navigation depending on the aligned position. From -1000 to +1000 any value in px. i.e. -30." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SoloArrowLeftHOffset, "The Offset position of the navigation depending on the aligned position. From -1000 to +1000 any value in px. i.e. -30. Each Arrow independent." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SoloArrowRightHOffset, "The Offset position of the navigation depending on the aligned position. From -1000 to +1000 any value in px. i.e. -30. Each Arrow independent." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SoloArrowLeftVOffset, "The Offset position of the navigation depending on the aligned position. From -1000 to +1000 any value in px. i.e. -30. Each Arrow independent." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SoloArrowRightVOffset, "The Offset position of the navigation depending on the aligned position. From -1000 to +1000 any value in px. i.e. -30. Each Arrow independent." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SwipeVelocity, "The Sensibility of Swipe Gesture (lower is more sensible) (Default: 0.7). Possible values: 0 - 1" },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SwipeMaxTouches, "Max Amount of Fingers to touch (Default: 1). Possible values: 1 - 5." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SwipeMinTouches, "Min Amount of Fingers to touch (Default: 1). Possible values: 1 - 5." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.DragBlockVertical, "Prevent Vertical Scroll on Drag." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.StartWithSlide, "Start with a Predefined Slide (index of the slide)." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.StopAtSlide, "Stop Timer if Slide 'x' has been Reached. If stopAfterLoops set to 0, then it stops already in the first loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.StopAfterLoops, "Stop Timer if All slides has been played 'x' times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideCaptionAtLimit, "Defines if a caption should be shown under a Screen Resolution (Based on the browser width)." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideAllCaptionAtLimit, "Hide all The Captions if browser width is less then this value." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideSliderAtLimit, "Hide the whole slider, and stop also functions if browser width is less than this value." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideNavDelayOnMobile, "Hide all navigation after a while on Mobile (touch and release events based)." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideThumbsOnMobile, "If set to 'on', thumbs are not shown on Mobile Devices." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideBulletsOnMobile, "If set to 'on', bullets are not shown on Mobile Devices." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideArrowsOnMobile, "If set to 'on', arrows are not shown on Mobile Devices." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideThumbsUnderResolution, "Possible Values: 0 - 1900. Defines under which resolution the thumbs should be hidden (only if hideThumbonMobile set to off)." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.Spinner, "The Layout of Loader. If not defined, it will use the basic spinner." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.HideTimerBar, "Hide or show the banner timer" },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.FullWidth, "Defines if the fullwidth/autoresponsive mode is activated." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.AutoHeight, "Defines if in fullwidth mode the height of the Slider proportional always can grow. If it is set to 'off' the max height is == startheight." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.MinHeight, "Defines the min height of the Slider. The Slider container height will never be smaller than this value. The Content container is still shrinks linear to the browser width and original width of Container, and will be centered vertically in the Slider." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.FullScreenAlignForce, "Allowed only in FullScreen Mode. It lets the Caption Grid to be the full screen, means all position should happen with aligns and offsets. This allow you to use the furthest corner of the slider to present any caption there." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.ForceFullWidth, "Force the FullWidth Size even if the slider embeded in a boxed container. It can provide higher Performance usage on CPU. Try first set it to 'off' and use fullwidth container instead of using this option." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.FullScreen, "Defines if the fullscreen mode is activated." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.FullScreenOffsetContainer, "The value is a Container ID or Class i.e. '#topheader' - The Height of Fullheight will be increased with this Container height!" },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.FullScreenOffset, "A px or % value which will be added/reduced of the Full Height Container calculation." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.Shadow, "Different Shadow Types." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.DottedOverlay, "Creates a Dotted Overlay for the Background images extra. Best use for FullScreen / fullwidth sliders, where images are too pixaleted." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.Parallax, "How the Parallax should act. On Mouse Hover movements and Tilts on Mobile Devices, or on Scroll (scroll is disabled on Mobiles!)" },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.ParallaxBgFreeze, "If it is off, the Main slide images will also move with Parallax Level 1 on Scroll." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.ParallaxLevels, "An array which defines the Parallax depths (0 - 10). Depending on the value it will define the Strength of the Parallax offsets on mousemove or scroll. In Layers you can use the class like rs-parallaxlevel-1 for the different levels. If one tp-caption layer has rs-parallaxlevel-X (x 1-10) then it activates the Parallax movements on that layer." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.ParallaxDisableOnMobile, "Turn on/off Parallax Effect on Mobile Devices." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.PanZoomDisableOnMobile, "Turn on/off Pan Zoom Effects on Mobile Devices." },
                    { LocalizableStrings.RevolutionSliderBlock.HelpText.SimplifyAll, "Set all Animation on older Browsers like IE8 and iOS4 Safari to Fade, without splitting letters to save performance." },
                };
            }
        }

        #endregion ILanguagePack Members
    }
}